(define (product1 n)
	(define (iter i n result)
		(if (> i n)
   			result
			(if (= 1 (remainder i 2))
				(iter (+ i 1) n (* result (/ (+ i 1) (+ i 2))))
	 			(iter (+ i 1) n (* result (/ (+ i 2) (+ i 1))))
			)
		)
	)
	(* 4 (iter 1 n 1))
)

(define (product2 n)
 	(define (iter i n)
 		(if (> i n)
			1
			(if (= 1 (remainder i 2))
				(* (/ (+ i 1) (+ i 2)) (iter (+ 1 i) n))
				(* (/ (+ i 2) (+ i 1)) (iter (+ 1 i) n))
			)
		)
   	)
)
